[package]
name = "lib-b"
version = "0.1.0"
authors = ["Trussed Developers"]
edition = "2018"

[dependencies.delog]
path = "../.."

[features]
# default = ["log-warn"]
default = []

log-error = []
log-warn = ["log-error"]
log-info = ["log-warn"]
log-debug = ["log-info"]
log-trace = ["log-debug"]
log-all = ["log-trace"]
log-none = []

