something:
	cargo run
	cargo run --no-default-features --features lib-a/log-all,lib-b/log-all
	cargo run --features lib-a/log-all,lib-b/log-all
	cargo run --features lib-a/log-all,lib-a1/log-all
	cargo run --features lib-b/log-all
	cargo run --features lib-a/log-trace,lib-b/log-error
