[package]
name = "qemu-tests"
version = "0.0.0"
authors = ["Trussed Developers"]
edition = "2018"
description = "Test salty using QEMU musca-b1"
license = "Apache-2.0 OR MIT"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.5"
panic-semihosting = { version = "0.5.3", features = ["exit"] }

[dependencies.delog]
path = ".."

[features]
default = ["log-all"]
log-all = []
log-none = []

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "z"
